### PR TITLE
Refactored main menu

### PR DESCRIPTION
**Pull request by drivasperez**
Hi,

I thought I'd take a look at the main menu and tidy it up a little. Changes made:

1. I made the menu into a class object, and changed the functions into class methods.
2. I made the `options` nested array into an unnested dict.
3. The main loop logic is a bit tidier, and uses error handling to catch invalid options. 
2. The program can now take some simple arguments to make it easier to use if you know exactly what you're looking to do. For example, `python sportsBook.py -s football` takes you directly to the football menu.

Thanks!

### CODE REVIEW

**Comment by Pringleman83** [comment]
This looks awesome, thanks! I'm off to work now so I'll load it up later and check it out. Really appreciate your efforts!
I've sent you the updated base which has some nice features too.

**Comment by drivasperez** [comment]
Thanks! I added a couple of minor changes now that it's no longer midnight.

**Comment by surister** [comment]
Looks fine overall but I can see that you have some python 2 habits, I will correct them on the upcoming pull requests

**Comment by surister** [comment]
Also your pr was made into :development: branch which is not Object oriented yet, so you might want to do it in experimental which is where we are currently doing it

**Comment by drivasperez** [comment]
Ah, good point! I've made another PR, will close this one.

**Pull request closed without merging**
